---
title: "Base rates for lab accidents causing pandemics"
author: "Joshua Blake"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
---

```{r}
library(brms)
library(broom)
library(dplyr)
library(gnlm)
library(ggplot2)
library(purrr)
library(tidyr)

logit = function(x) log(x) - log1p(x)
expit = function(x) 1 / (1 + exp(-x))
```

Choose some paramters

```{r}
true_params = list(
    a = 9000,
    b = 0.06,
    c = 35
)
print(true_params)
```

Simulate some data

```{r}
data = tibble(
    time = 1950:2020,
    true_articles = true_params$a * expit(true_params$b * (time - 1950 - true_params$c)),
) |>
    mutate(
        n = rpois(n(), true_articles),
    )
data |>
    ggplot(aes(time, n)) +
    geom_point() +
    geom_line(aes(y = true_articles), color = "red") +
    theme_minimal() +
    coord_cartesian(ylim = c(0, 10e3))
```

NLS fit

```{r}
fit_nls = nls(
    n ~ a * expit(b * (time - 1950 - c)),
    data = data,
    start = list(a = 1000, b = 0.01, c = 70)
)
summary(fit_nls)
```

This works, how about with Poisson likelihood?

```{r}
# Use gnlr function from the gnlm package to fit model
mean_func = function(p) {
    exp(p[1] - log1p(exp(-p[2] * (data$time - 1950 - p[3]))))
}
gnlr(
    data$n,
    mu = mean_func,
    pmu = c(log(1000), 0.01, 70),
    distribution = "Poisson"
)
```

Also looks good.

Now try Bayesian.
```{r}
fit_brms = brm(
    bf(
        n ~ exp(a) * inv_logit(b * ((time - 1950) - c)),
        a + b + c ~ 1,
        # max ~ type - 1,
        nl = TRUE
    ),
    data = data,
    prior = prior(normal(0, 0.1), nlpar = "b") +
        prior(exponential(0.01), nlpar = "c", lb = 0) + 
        prior(normal(0, 10), nlpar = "a", lb = 0),
    family = poisson("identity"),
    cores = 4,
    init = function() list(
        a = log(1000),
        b = 0.01,
        c = 70
    )
)
summary(fit_brms)
all_counts |>
    add_predicted_draws(fit_brms) |>
    median_qi() |>
    ggplot(aes(year, .prediction, ymin = .lower, ymax = .upper)) +
    geom_lineribbon(alpha = 0.3) +
    geom_point(aes(y = n)) +
    facet_wrap(~type, scales = "free_y") +
    theme_minimal()
```